name = "Invited Talks and Panels"

[2021]
[[engagements]]
organization = "Indiana University Departments of Neuroscience and Cognitive Science"
title = "IU Neuroscience / Cognitive Science Joint Colloquium Series"
date = "March 29"
location = "Virtual"
asset = ""

[2020]
[[engagements]]
organization = "University of Michigan Department of Psychology"
title = "Cognition & Cognitive Neuroscience Area Forum"
date = "November 13"
location = "Virtual"
asset = "https://events.umich.edu/event/79117"

[[engagements]]
organization = "New York University Department of Psychology"
title = "Industry Careers Panel"
date = "November 9"
location = "Virtual"
asset = ""

[[engagements]]
organization = "University of Washington Data Science for Social Good"
title = "Data Science for Social Good Panel: Nonprofit"
date = "July 31"
location = "Virtual"
asset = "https://escience.washington.edu/2020-data-science-for-social-good-projects/"

[[engagements]]
organization = "University of Califonia at San Diego"
title = "Intro to Data Science Guest Lecture"
date = "March 5"
location = "San Diego, CA"
asset = ""

[[engagements]]
organization = "New York University Graduate School of Arts and Science"
title = "Panel on PhD Industry Job Search Panel"
date = "February 19"
location = "New York, NY"
asset = ""

[2019]
[[engagements]]
organization = "City College of New York Association of Computing Machinery"
title = "How to Open Source Panel"
date = "November 7"
location = "New York, NY"
asset = "https://www.eventbrite.com/e/how-to-open-source-panel-tickets-79082246127"

[[engagements]]
organization = "csv,conf"
title = "csv,conf,v4 Keynote"
date = "May 9"
location = "Portland, OR"
asset = ["https://www.youtube.com/watch?v=0_Ws9t9FGqA&feature=youtu.be",
         "https://doi.org/10.5281/zenodo.2766123"]

[[engagements]]
organization = "Duke University Cognition and Cognitive Neuroscience"
title = "CCN Colloquium Series"
date = "February 1"
location = "Durham, NC"
asset = "https://dibs.duke.edu/events/teon-brooks-mozilla"

[[engagements]]
organization = "The University of North Carolina at Chapel Hill Psychology and Neuroscience"
title = "Cognitive Talk Series"
date = "January 31"
location = "Chapel Hill, NC"
asset = "https://psychology.unc.edu/event/cognitive-talk-81/"

[2018]
[[engagements]]
organization = "Society for Neuroscience"
title = "FAIR Neuroscience: Sharing and Collaborating for Reproducible Data Workshop"
date = "November 5"
location = "San Diego, CA"
asset = ["https://www.sfn.org/annual-meeting/neuroscience-2018/sessions-and-events/professional-development-workshops#Monday-November-05-2018",
         "https://neuronline.sfn.org/professional-development/data-sharing-principles-to-promote-open-science",
         "https://doi.org/10.5281/zenodo.3245441"]


[2017]
[[engagements]]
organization = "Entomological Society of America"
title = "Organizing a national March for Science"
date = "November 8"
location = "Denver, CO"
asset = "https://esa.confex.com/esa/2017/meetingapp.cgi/Paper/127628"

[[engagements]]
organization = "CLEO Conference"
title = "Scientist + Advocacy Panel"
date = "May"
location = "San Jose, CA"
asset = ""

[[engagements]]
organization = "Mozilla"
title = "March for Science chat with Mozilla Science Fellow, Teon Brooks"
date = "April 19"
location = "San Francisco, CA"
asset = "https://www.facebook.com/mozilla/videos/march-for-science-chat-with-mozilla-science-fellow-teon-brooks/10155126293402381/"

[[engagements]]
organization = "Tested: Offworld"
title = "Arrival"
date = "December"
location = "San Francisco, CA"
asset = "https://www.tested.com/podcasts/offworld/872230-offworld-arrival-2016/"

[[engagements]]
organization = "Maker Faire"
title = "The Accessible Future of Neuroscience Panel"
date = "October"
location = "New York, NY"
asset = "https://makerfaire.com/maker/entry/58916/"

[[engagements]]
organization = "New York University Graduate School of Arts and Science"
title = "Doctoral Convocation: Student Speaker"
date = "May"
location = "New York, NY"
asset = "www.nyu.edu/about/news-publications/news/2016/may/class-of-2016-commencement-profiles.html#brooks"

[[engagements]]
organization = ""
title = ""
date = ""
location = ""
asset = ""
