[[honor]]
title = "Carolina Covenant Scholarship"
issuer = "University of North Carolina at Chapel Hill"
awarded = "2006"
description = """
2006–2009.
"""

[[honor]]
title = "Mary and Maurice Julian Scholarship"
issuer = "University of North Carolina at Chapel Hill"
awarded = "2006"
description = """
2006–2009.
"""

[[honor]]
title = "NYU Summer Research Fellowship"
issuer = "New York University"
awarded = "2011"
description = """
2011–2014.
"""

[[honor]]
title = "NYU MacCracken Fellowship"
issuer = "New York University"
awarded = "2011"
description = """
2011–2016.
"""

[[honor]]
title = "Society for the Neurobiology of Language Travel Award"
issuer = "Society for the Neurobiology of Language"
awarded = "2011"
description = """

"""

[[honor]]
title = "National Science Foundation Graduate Research Fellowship"
issuer = "National Science Foundation"
awarded = "2011-04"
description = """
2011–2016.
"""

[[honor]]
title = "Society for the Neurobiology of Language Travel Award"
issuer = "Society for the Neurobiology of Language"
awarded = "2013"
description = """

"""

[[honor]]
title = "Society of Multivariate Experimental Psychology Travel Award"
issuer = "Society of Multivariate Experimental Psychology"
awarded = "2013"
description = """

"""

[[honor]]
title = "National Science Foundation Graduate Research Opportunities Worldwide"
issuer = "National Science Foundation"
awarded = "2014"
description = """
$5,000 award.
"""

[[honor]]
title = "Chateaubriand STEM Fellowship"
issuer = "Embassy of France in Washington, D.C"
awarded = "2014-05"
description = """
Fellowship to support research at Telecom ParisTech.
"""

[[honor]]
title = "American Delegate"
issuer = "Lindau Nobel Laureate Meetings"
awarded = "2014-06"
description = """
The 64th Lindau Nobel Laureate Meeting 2014 for Physiology/Medicine

Part of the 2014 US Delegation for Physiology or Medicine
"""

[[honor]]
title = "NYU Prototyping Fund"
issuer = "New York University"
awarded = "2015"
description = """
$500 grant.
"""

[[honor]]
title = "Open and Collaborative Science in Development Network"
issuer = "OCSDNet"
awarded = "2016"
description = """
$1,500 grant.
"""

[[honor]]
title = "NYU President's Service Award"
issuer = "New York University"
awarded = "2016-04"
description = """
"For impactful work in various organizations focused on the promotion of student life in his GSAS cohort and the Neuroscience community."
"""

[[honor]]
title = "Mozilla Fellowship for Open Science"
issuer = "Mozilla Foundation"
awarded = "2016-09"
description = """
2016–2017.
"""
