[id]
name = "Teon L Brooks, Ph.D"
imageURL = "https://0.gravatar.com/avatar/8179ec2a3461f51e568637a913b4061ebc7d6d31d7a1aad43d0e251b1fe42c0b?size=1000"
# imageURL = "images/home.jpg"
short_bio = """
Teon L. Brooks, Ph.D is the co-founder of the nonprofit, [Gotham Data Clinic](https://gothamdataclinic.org) and a data scientist working with the [Brain & AI team](https://kingjr.github.io/images/team.png) at Meta FAIR.

Dr. Brooks has expertise in data science, open-source software development, neuroimaging, and neuroinformatics.
His research background in psycholinguistics, cognitive science, and data science education.

Outside of research, Teon has also been working a new project, [passports.social](https://passports.social) (pre-alpha), a new [open social app](https://atmosphereaccount.com) focused on life logging and discovery.

He posts on Bluesky 🦋 at [@teonbrooks.com](https://bsky.app/profile/teonbrooks.com).
"""
location = "Brooklyn, NY, US"
[[id.social]]
Bluesky = "https://bsky.app/profile/teonbrooks.com"
GitHub = "https://github.com/teonbrooks"
LinkedIn = "https://linkedin.com/in/teonbrooks"
ORCID = "https://orcid.org/0000-0001-7344-3230"
Website = "https://teonbrooks.com"

[[id.descriptors]]
title = "Scientist"
website = "https://orcid.org/0000-0001-7344-3230"

[[id.descriptors]]
title = "Technologist"
website = "https://github.com/teonbrooks"

[[id.occupations]]
title = 'President'
organization = 'Gotham Data Clinic'
website = "https://gothamdataclinic.org"

[[id.occupations]]
title = 'Data Scientist'
organization = 'Brain & AI, Meta FAIR'
website = "https://ai.meta.com/research/publications/a-foundation-model-of-vision-audition-and-language-for-in-silico-neuroscience/"

[skills]

natural_languages =	["English (native)", "Portuguese (B1)", "French (B2)"]
programming_languages =	["Python (adv.)", "R (adv.)", "JavaScript (int.)"]

[[positions]]
filename = "covenant.png"
organization = "Carolina Covenant"
title = "Scholar"
timespan = "2006-2009"
description = """
Funding initiative for low-income students to graduate from college debt-free through grants, scholarships, and work-study.
"""
website = "https://www.unc.edu/story/carolina-covenant/"
category = "Fellowships"

[[positions]]
filename = "unc.png"
organization = "University of North Carolina at Chapel Hill"
title = "Research Lab Manager"
timespan = "2007-2011-07"
description = """
### Research Assistant (2007–2008)

Research Assistant in neurobiology.

Advisor: Dr. Mohanish Deshmukh.

### Research Lab Manager (2008–2011)

Manage a language comprehension research lab focused on eye-tracking research.

Perform research on word recognition while reading.

Advisor: Dr. Peter C. Gordon.
"""
website = "https://unc.edu"
category = "Education"

[[positions]]
filename = "grfp.png"
organization = "National Science Foundation Graduate Research Fellowship Program"
title = "NSF Graduate Research Fellow"
timespan = "2011-2016"
description = """
Fellowship recipient in prestigious national competition for graduate-level STEM Research.
"""
website = "https://nsfgrfp.org"
category = "Fellowships"

[[positions]]
filename = "nyu.png"
organization = "New York University"
title = "Doctoral Student"
timespan = "2011-09-2017-05"
description = """
### Doctoral Student (2011–2017)

Ph.D. in Experimental Psychology: Cognition and Perception. Dissertation: "Minding the Gap between Eye-tracking and Neurophysiology in Reading." Committee: Dr. Alec Marantz, Dr. David Poeppel, Dr. Brian McElree.

President, NYU Cog Collective (2015–2017) — cofounder of the student organization representing the Cognition and Perception program; organized workshops and hosted socials.

### Teaching Assistant (2012)

PSYCH.UA.0300-007: Lab in Cognitive Neuroscience. Professor: Dr. David Poeppel.
"""
website = "https://as.nyu.edu/psychology.html"
category = "Education"

[[positions]]
filename = "mne.png"
organization = "MNE-tools"
title = "Maintainer"
timespan = "2012-2023"
description = """
MNE-Python: Maintainer (2012-2019)
MEG and EEG Data Processing and Analysis Package in Python.

MNE-BIDS: Maintainer (2017-2020)
Read and write BIDS-compatible datasets with the help of MNE-Python in Python.

MNE-Realtime: Maintainer (2019-2023)
Supported realtime data analysis with support for LSL and FieldTrip clients. This project has been deprecated and superseded by mne-lsl.
"""
website = "https://mne.tools"
category = ["Research Software Engineering"]

[[positions]]
filename = "chateaubriand.png"
organization = "French Embassy to the U.S."
title = "STEM Fellow"
timespan = "2014-2015"
description = """
Fellowship to conduct dissertation research in France.
"""
website = "https://chateaubriand-fellowship.org/"
category = "Fellowships"

[[positions]]
filename = "telecom.png"
organization = "Télécom Paris"
title = "Visiting Research Fellow"
timespan = "2014-07-2015-07"
description = """
Visiting research fellow sponsored by the French Embassy's Chateaubriand Graduate Research Fellowship. Acquired digital signal processing training. Acquired data analysis skills of electrophysiological data. Acquired machine learning training.

Advisor: Dr. Alexandre Gramfort.
"""
website = ""
category = "Education"

[[positions]]
filename = "openexp.png"
organization = "OpenEXP"
title = "Product Lead"
timespan = "2015-2017"
description = """
An open-source platform for running experiments with jsPsych and collect behavioral and physiological data.
"""
website = "https://github.com/openexp/OpenEXP/"
category = ["Past Projects"]

[[positions]]
filename = "openbci.png"
organization = "datalus"
title = "Principal Consultant"
timespan = "2015-08-Present"
description = """
OpenBCI — Consultant: Research Scientist (2015-08 – 2016-06)
Establishing validation and testing protocols for EEG hardware. Developing SDKs and APIs for OpenBCI Hardware. Developing an open-source software platform for running experiments, stream data for real-time analytics. Advising on research applications of wireless EEG.

BrainWaves — Consultant: Product Manager (2017–2022)
Led the end-to-end development of a novel all-in-one experimentation platform and application designed for teaching, developing, and conducting EEG-based psychology and neuroscience experiments. Conducted co-design and co-development practices to create the app for high school students and their teachers. Implemented the app in the classroom, reaching 10 schools with 30 students in each class.

Memorial Sloan Kettering, Gerstner Sloan Kettering — Consultant: Instructor (2025–Present)
Instructor for G440: Introduction to Scientific Python. https://github.com/datalus-dev/gsk-intro-scientific-python-course
"""
website = "https://openbci.com"
category = ["Past Orgs","Consulting"]

[[positions]]
filename = "msl.png"
organization = "Mozilla Science Lab"
title = "Fellow for Open Science"
timespan = "2016-2017"
description = """
10-month fellowship.
"""
website = "https://wiki.mozilla.org/ScienceLab"
category = "Fellowships"

[[positions]]
filename = "stanford.png"
organization = "Stanford University"
title = "Mozilla Fellow for Open Science, Postdoctoral Scholar"
timespan = "2016-09-2017-12"
description = """
Open Science + Open Source
I spent my tenure as a Mozilla Fellow for Open Science advocating for the use of open and transparent practices in science. I traveled globally teaching workshops on using open-source technologies, and speaking at conferences.

During the fellowship, I became one of the national organizers for the March for Science in Washington, DC. I worked as the Co-Director of Partnerships bringing in over 300 partner organizations to help mobilize scientists and science advocates. This event brought together more than a million people in over 600 cities worldwide.

I also worked on a project to build software that enables experimental psychologists and neuroscientists to freely share the experiment protocols and execute their experiments using open-source, and web-based technologies.

During my postdoc at Stanford, I was a core contributor to [1] the Brain Imaging Data Structure project for the inclusion of MEG into the specification, and to [2] the MNE-BIDS project to provide a software implementation.

Through this project, I hope to build community and code that improve the state of brain science research.

Advisor: Dr. Russell Poldrack.

[1] https://bids.neuroimaging.io/ ; https://www.nature.com/articles/sdata2018110
[2] https://github.com/mne-tools/mne-bids ; https://joss.theoj.org/papers/10.21105/joss.01896
"""
website = "https://stanford.edu"
category = "Education"

[[positions]]
filename = "bids.png"
organization = "Brain Imaging Data Structure (BIDS)"
title = "Core Contributor"
timespan = "2017-2020"
description = """
A community-driven data sharing standardization.
"""
website = "https://bids.neuroimaging.io"
category = ["Research Software Engineering"]

[[positions]]
filename = "brainwaves.png"
organization = "BrainWaves"
title = "Product Lead"
timespan = "2017-2022"
description = """
An easy-to-use platform for EEG experimentation in the classroom.
"""
website = "https://github.com/makebrainwaves/BrainWaves"
category = ["Past Projects"]

[[positions]]
filename = "firefox.png"
organization = "Mozilla Corporation"
title = "Staff Data Scientist"
timespan = "2017-11-2024-07"
description = """
### Senior Data Scientist (2017–2020)

Designed and executed A/B tests and other experiments to drive new product development and optimize the search experience within Firefox.
Leveraged non-parametric statistical methods to conduct large-scale data analysis and modeling on datasets of hundreds of millions of users to better understand how users engage with our search products.
Combined survey methods with observational studies of browser usage to understand how user sentiment maps onto user behavior with their interactions with search in Firefox.
Mentored two data scientist interns on exploratory data analysis and data science practices.
Launched and managed the Data@Mozilla blog.

### Senior Product Manager, Machine Learning (2021–2022)

Led the strategic development and implementation of on-device machine learning capabilities within new browser products.
Designed robust telemetry instrumentation to enable contextual recommendation within Firefox.
Mentored students at the AUC Data Science Initiative on responsible and trustworthy AI within product development and design.

### Staff Data Scientist (2024)

Designed and implemented experimentation frameworks for novel machine-learning powered search suggestions and user experiences within Firefox Suggest, a novel first-party search product.
Conducted in-depth exploratory data analyses on datasets encompassing hundreds of millions of users, extracting critical insights to inform revenue and advertising strategies.
Designed and implemented derivative data tables to provide granular understanding and reporting on key performance indicators within the search and advertising business.
"""
website = "https://mozilla.org"
category = ["Past Orgs"]

[[positions]]
filename = "ciel.png"
organization = "Gotham Data Clinic"
title = "President"
timespan = "2019-11-Present"
description = """
We are the Gotham Data Clinic, and we are focused on researching, building, and sharing data science education tools for the next generation of scientists and technologists.

Originally founded in 2019 as CiELabs, the nonprofit was on hiatus through the pandemic. In 2023, we rebranded and refocused our efforts.

Founded and established the nonprofit from its incorporation through its application for federal tax exemption. Lead workshops on data literacy with partner organizations. Build new partnerships with NYC Public Schools and CUNY. Lead product development work for new digital infrastructure to teach data science at scale. Write scholarly work to support both our community and product development work.
"""
website = "https://gothamdataclinic.org"
category = "Current Orgs"

[[positions]]
filename = "american.png"
organization = "American University"
title = "Adjunct Senior Professorial Lecturer"
timespan = "2021-01-2021-05"
description = """
STAT 412/612: Teaching graduate/advanced-undergraduate level Statistical Programming in R
- Foundations in R
- Foundation in Tidyverse
- Data Exploration, Transformation, Analysis, and Modeling
"""
website = ""
category = ["Past Orgs","Teaching"]

[[positions]]
filename = "aimlabs.png"
organization = "Statespace"
title = "VP: Head of Product, Research and Development"
timespan = "2022-05-2022-10"
description = """
Launched and delivered a joint product venture between the core product team and R&D, to create a mouse sensitivity finder for first-person shooter gaming, based off of my team’s research. Led cross-functional product initiatives with product and engineering teams. Led and mentored a team of five research scientists and one research assistant to publish research on motor acuity and successfully integrate key research insights into Aim Lab, the flagship aim trainer product. Led and coordinated digital health initiatives in partnership with clinics and university football teams to develop cognitive assessments for altered states of consciousness, including concussion. Impacted by a substantial company-wide reduction of workforce, which led to the cancellation of the R&D function.
"""
website = "aimlabs.com"
category = "Past Orgs"

[[positions]]
filename = "sabbatical.png"
organization = ""
title = "Personal Sabbatical"
timespan = "2022-11-2023-12"
description = """
Undertook an extended period of personal time off for bereavement, and for personal development. Enhanced web development and machine learning skills through intensive professional development at the Recurse Center.
"""
website = ""
category = ["Past Orgs"]

[[positions]]
filename = "recurse.png"
organization = "Recurse Center"
title = "Recurser"
timespan = "2023-05-2025-02"
description = """
### Recurser (2023)

Summer 1 Half-Batch.

### Recurser (2024–2025)

Full-stack engineering: Svelte(kit) + Supabase Machine Learning Engineering: Keras + PyTorch + Sklearn
"""
website = "https://recurse.com"
category = "Education"

[[positions]]
filename = "brain.png"
organization = "Meta (United States)"
title = "Data Scientist"
timespan = "2025-08-Present"
description = """
Leads the development of NeuralFetch and contributes to the NeuroAI open-source software suite to download, validate, and analyze multimodal neuroscience datasets (fMRI, MEG, EEG, iEEG, fNIRS, EMG).
Standardizes public datasets for ingestion and validates research studies using machine learning decoding techniques.
Develops an automated validation and replication framework for neuroscience research projects.

(Meta via Magnit)
"""
website = ""
category = ["Current Orgs"]

[[positions]]
filename = "cuny.png"
organization = "City University of New York"
title = "Adjunct Assistant Professor"
timespan = "2026-01-2026-05"
description = """
College of Staten Island. Spring 2026 - EDD 642: Creative Computing in Education.
"""
website = ""
category = ["Current Orgs","Teaching"]
