[portfolio]
name = "Teon L Brooks, Ph.D"

[[positions]]
icon = "brainwaves.png"
organization = "BrainWaves"
title = "President of Advisory Board"
timespan = "2017-Present"
description = ""
website = "https://wp.nyu.edu/brainwaves/"

[[positions]]
icon = "chateaubriand.png"
organization = "French Embassy to the U.S."
title = "STEM Fellow"
timespan = "2017-2018"
description = "Served on the board of a nonprofit advocacy group for early-career scientists."
website = "https://futureofresearch.org"

[[positions]]
icon = "ciel.png"
organization = "Computation in Education Labs"
title = "Executive Director"
timespan = "2019-Present"
description = ""
website = "https://cielabs.org"

[[positions]]
icon = "covenant.png"
organization = "Carolina Covenant"
title = "Scholar"
timespan = "2006-2009"
description = ""
website = ""

[[positions]]
icon = "firefox.png"
organization = ""
title = ""
timespan = ""
description = ""
website = ""

[[positions]]
icon = "FoR.png"
organization = "Future of Research"
title = "Board Member"
timespan = "2017-2018"
description = "Served on the board of a nonprofit advocacy group for early-career scientists."
website = "https://futureofresearch.org"

[[positions]]
icon = "grfp.png"
organization = ""
title = ""
timespan = ""
description = ""
website = ""

[[positions]]
icon = "mfs.png"
organization = "March for Science"
title = "Co-Director of Partnerships"
timespan = "2017"
description = """
Co-led a team to build a coalition of >300 scientific
societies, NGOs, science museums, and non-profits to mobilize their
members to march. Organized and coordinated one of the largest science
demonstration with 100k marchers in DC and over a million marchers in
610 cities worldwide.
"""
website = "https://marchforscience.org"

[[positions]]
icon = "msl.png"
organization = ""
title = ""
timespan = ""
description = ""
website = ""

[[positions]]
icon = "nyu.png"
organization = "New York University"
title = "PhD Student"
timespan = "2011-2017"
description = ""
website = ""

[[positions]]
icon = "openbci.png"
organization = ""
title = ""
timespan = ""
description = ""
website = ""

[[positions]]
icon = "openexp.png"
organization = "OpenEXP"
title = ""
timespan = ""
description = ""
website = ""

[[positions]]
icon = "queerhack.png"
organization = "QueerHack"
title = ""
timespan = ""
description = ""
website = ""

[[positions]]
icon = "shd.png"
organization = "Science Hack Day"
title = ""
timespan = ""
description = ""
website = ""

[[positions]]
icon = "stanford.png"
organization = "Stanford University"
title = ""
timespan = ""
description = ""
website = ""

[[positions]]
icon = "telecom.png"
organization = "Telecom ParisTech"
title = ""
timespan = ""
description = ""
website = ""

[[positions]]
icon = "trainer-hex.png"
organization = "RStudio"
title = "Certified Trainer"
timespan = ""
description = ""
website = ""

[[positions]]
icon = "unc.png"
organization = "University of North Carolina"
title = "Bachelor of Science"
timespan = "2005-2009"
description = ""
website = ""

[[positions]]
icon = ""
organization = ""
title = ""
timespan = ""
description = ""
website = ""

